# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'knavigations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for knavigations

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'knavigationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
